services:
  web:
    build: .
    working_dir: /app
    command: >
      sh -c "
      until pg_isready -h db -p 5432; do sleep 1; done &&
      uv run python manage.py migrate &&
      uv run python manage.py create_perms &&
      uv run python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(email_address='admin@example.com').exists() or User.objects.create_superuser('admin@example.com', 'admin')\" &&
      uv run uvicorn e_learning_backend.asgi:application --host 0.0.0.0 --port 8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: e_learning_db
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: e_learning_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d e_learning_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:



# services:
#   web:
#     build: .
#     command: >
#       sh -c "uv run python manage.py migrate &&
#       uv run python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(email_address='admin@example.com').exists() or User.objects.create_superuser('admin@example.com', 'admin')\" &&
#       uv run uvicorn e_learning_backend.asgi:application --host 0.0.0.0 --port 8000"
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     environment:
#       DB_NAME: e_learning_db
#       DB_USER: admin
#       DB_PASSWORD: admin123
#       DB_HOST: db
#       DB_PORT: 5432
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: e_learning_db
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: admin123

# volumes:
#   postgres_data:
